# Data
data_type: brain                  # data type: brain knee
mask_type: cartesiancs            # mask: poisson, cartesian, cartesianrandom, cartesiancs, radial
sampling_factor: 8                # UnderSampling factor
n_coils: 8                        # Coils Number
add_noise: False                  # Add extra Guassian Noise or not
noise_level: 0.2                  # Noisel level
img_size: 320                     # size of training images
label_index_train:                # Samples for training
    - 0
    - 5017     
label_index_val:                  # Samples for validation
    - 0
    - 524

---
# Model
model_name: VSNet             # model: UNet, FUNet, MoDL, FMoDL, SwinMR
alfa: 0.1                     
beta: 0.1
cascades: 5
dwconv: True

---
# Training parameters
optimizer: Adam              # optimizer: RMSprop, Adma
LR: 1e-3
weight_decay: 0           
momentum: 0.9                
loss: MSE                    # loss function: L1, MSE
epoches: 200                 # total training epoches
batch_size: 16               # barch size
repara: False
return_shift: True

---
# Save and load
save_dir: './export'
save_sub_dir: ''
save_label: ''
resume_training: False

# other
device: cuda
vis_interval: 50             # print loss for every ? step